name: zhasqoldau
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  get_it: ^7.2.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/